### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Kra1o5**

### CODE REVIEW

**Review by andDevW — COMMENTED** [review]
Moving past SDK25 will require some clever workarounds in GetChromium.java, and the current release works great in the latest Android P beta preview. If you remove the Update to O I'll merge the Spanish language addition.

**Review by andDevW — APPROVED** [review]

**Comment by Kra1o5** [comment]
ok, I will do, but only break getChromium if we change targetsdkversion.

**Comment by Kra1o5** [comment]
@andDevW,
Changes updated.

**Review by andDevW — CHANGES_REQUESTED** [review]
Not going to merge broken code.

**Pull request closed without merging**
