### PR TITLE
Show download progress

### PR DESCRIPTION
**Pull request by XyLoNaMiyX**

### CODE REVIEW

**Comment by andDevW** [comment]
After testing I decided to pass on this one.
It feels odd to go from a finite progress dialog with the download to an 
[indeterminite](https://github.com/andDevW/getChromium/blob/res/getChromium_RES/device-2016-03-25-185827.png) progress dialog with the application installer. 
For the time being, the whole process will remain a somewhat unpredictable duration event.
If Google makes a change to the installer progress dialog then I'll change to keep consistent with that.

**Comment by XyLoNaMiyX** [comment]
Download is usually a long process (longer than most installations anyway). I think the more information and feedback we can provide to the user the better. I respect your decission nevertheless, it's your application after all :)

**Comment by andDevW** [comment]
The package manager in Android O has a determinate progress dialog, so I'm accepting your pull request in [v4.1-beta-1](https://github.com/andDevW/getChromium/releases/tag/v4.1-beta-1). If you submit a new pull request for this issue I'll gladly accept it in v4.1-beta-2.

**Comment by Lonami** [comment]
I personally use another application for this  now (edit this message to see it), so this is no longer an issue for me, sorry! However, if you feel like reusing my code would be easier than implementing it again on the current state of the project, go ahead, you don't need to credit me :P

**Pull request closed without merging**
